In [14]:
import sklearn.preprocessing
import dask_ml.preprocessing
import numpy as np
import dask.array as da
import dask.dataframe as dd
import pandas as pd

In [15]:
X = np.array([['a', 'b', 'a', 'c']]).T
X

array([['a'],
       ['b'],
       ['a'],
       ['c']], dtype='<U1')

### Benchmark

In [16]:
categories = [['a', 'b', 'c']]

### Dask Array

In [18]:
dx = da.from_array(X, chunks=2)
dx 

dask.array<array, shape=(4, 1), dtype=<U1, chunksize=(2, 1)>

In [24]:
enc = dask_ml.preprocessing.OneHotEncoder(sparse=False, categories=categories)
enc.fit_transform(dx)

dask.array<lambda, shape=(4, 3), dtype=float64, chunksize=(2, 3)>

In [27]:
x2 = da.from_array(np.array([['a'], ['c']]), 2)
enc.transform(x2).compute()

array([[1., 0., 0.],
       [0., 0., 1.]])

In [7]:
dask_ml.preprocessing.OneHotEncoder(sparse=False).fit_transform(da.concatenate([dx, dx], axis=1).rechunk({1: -1})).compute()

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [8]:
df = pd.DataFrame({"A": ['a', 'b', 'a', 'c']}, dtype='category')

In [9]:
sklearn.preprocessing.OneHotEncoder(sparse=False).fit_transform(df)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [10]:
dask_ml.preprocessing.OneHotEncoder(sparse=False).fit_transform(df)

A_a  A_b  A_c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0

In [11]:
ddf = dd.from_pandas(df, 2)

In [13]:
dask_ml.preprocessing.OneHotEncoder(sparse=False).fit_transform(ddf.A)

ValueError: Expected 2D array, got 1D array instead:
array=['a' 'b' 'a' 'c'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
k
